version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: react_app
    ports:
      - "3000:80"
